name: Static analysis

on: push

jobs:
  call-secrets-analysis-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.13.2

  call-ruff-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-ruff.yml@v0.13.2
